spring:
  application:
    name: todo-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:todo}
    username: ${POSTGRES_USER:todo}
    password: ${POSTGRES_PASSWORD:todo}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_Zm7eSn6ht
